admin_tag_index:
    path:     /
    defaults: { _controller: "GameBundle:Tag:index" }
    methods:  GET

admin_tag_show:
    path:     /{id}/show
    defaults: { _controller: "GameBundle:Tag:show" }
    methods:  GET

admin_tag_new:
    path:     /new
    defaults: { _controller: "GameBundle:Tag:new" }
    methods:  [GET, POST]

admin_tag_edit:
    path:     /{id}/edit
    defaults: { _controller: "GameBundle:Tag:edit" }
    methods:  [GET, POST]

admin_tag_delete:
    path:     /{id}/delete
    defaults: { _controller: "GameBundle:Tag:delete" }
    methods:  DELETE
