Badger\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: Badger\UserBundle\Doctrine\Repository\UserRepository
    fields:
        id:
            id: true
            type: guid
            generator:
                strategy: UUID
        github_id:
            type: string
            length: 255
            nullable: true
        github_access_token:
            type: string
            length: 255
            nullable: true
        google_id:
            type: string
            length: 255
            nullable: true
        google_access_token:
            type: string
            length: 255
            nullable: true
        profilePicture:
            type: string
            nullable: true
    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
        tags:
            targetEntity: Badger\TagBundle\Entity\Tag
            joinTable:
                name: users_tags
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    oneToMany:
        badge_votes:
            targetEntity: Badger\GameBundle\Entity\BadgeVote
            mappedBy: user
