services:
    badger.tags.saver.tag:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\Bundle\TagBundle\Entity\Tag'
