parameters:
    badger.tag.repository.tag.class: Badger\TagBundle\Doctrine\Repository\TagRepository

services:
    badger.tag.repository.tag:
        class: '%badger.tag.repository.tag.class%'
        factory: [doctrine.orm.entity_manager, getRepository]
        arguments:
            - Badger\TagBundle\Entity\Tag
