admin_user_index:
    path:     /
    defaults: { _controller: "UserBundle:User:index" }
    methods:  GET

admin_user_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:User:show" }
    methods:  GET

admin_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:User:edit" }
    methods:  [GET, POST]

admin_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:User:delete" }
    methods:  DELETE
