parameters:
    badger.game.repository.badge.class: Badger\GameBundle\Doctrine\Repository\BadgeRepository
    badger.game.repository.quest.class: Badger\GameBundle\Doctrine\Repository\QuestRepository
    badger.game.repository.claimed_badge.class: Badger\GameBundle\Doctrine\Repository\ClaimedBadgeRepository
    badger.game.repository.unlocked_badge.class: Badger\GameBundle\Doctrine\Repository\UnlockedBadgeRepository
    badger.game.repository.quest_completion.class: Badger\GameBundle\Doctrine\Repository\QuestCompletionRepository
    badger.game.repository.adventure.class: Badger\GameBundle\Doctrine\Repository\AdventureRepository
    badger.game.repository.adventure_step.class: Badger\GameBundle\Doctrine\Repository\AdventureStepRepository
    badger.game.repository.adventure_step_completion.class: Badger\GameBundle\Doctrine\Repository\AdventureStepCompletionRepository

services:
    badger.game.repository.badge:
        class: '%badger.game.repository.badge.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\Badge

    badger.game.repository.quest:
        class: '%badger.game.repository.quest.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\Quest

    badger.game.repository.claimed_badge:
        class: '%badger.game.repository.claimed_badge.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\ClaimedBadge

    badger.game.repository.unlocked_badge:
        class: '%badger.game.repository.unlocked_badge.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\UnlockedBadge

    badger.game.repository.quest_completion:
        class: '%badger.game.repository.quest_completion.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\QuestCompletion

    badger.game.repository.adventure:
        class: '%badger.game.repository.adventure.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\Adventure

    badger.game.repository.adventure_step:
        class: '%badger.game.repository.adventure_step.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\AdventureStep

    badger.game.repository.adventure_step_completion:
        class: '%badger.game.repository.adventure_step_completion.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Badger\GameBundle\Entity\AdventureStepCompletion
