parameters:
    badger.game.badge.factory.class: Badger\GameBundle\Factory\BadgeFactory
    badger.game.quest.factory.class: Badger\GameBundle\Factory\QuestFactory
    badger.game.unlocked_badge.factory.class: Badger\GameBundle\Factory\UnlockedBadgeFactory
    badger.game.claimed_badge.factory.class: Badger\GameBundle\Factory\ClaimedBadgeFactory
    badger.game.quest_completion.factory.class: Badger\GameBundle\Factory\QuestCompletionFactory
    badger.game.adventure.factory.class: Badger\GameBundle\Factory\AdventureFactory

services:
    badger.game.badge.factory:
        class: '%badger.game.badge.factory.class%'

    badger.game.quest.factory:
        class: '%badger.game.quest.factory.class%'

    badger.game.unlocked_badge.factory:
        class: '%badger.game.unlocked_badge.factory.class%'

    badger.game.claimed_badge.factory:
        class: '%badger.game.claimed_badge.factory.class%'

    badger.game.quest_completion.factory:
        class: '%badger.game.quest_completion.factory.class%'

    badger.game.adventure.factory:
        class: %badger.game.adventure.factory.class%
