game:
    resource: "@GameBundle/Controller/"
    type:     annotation

game_admin_badge:
    resource: "@GameBundle/Resources/config/routing/badge.yml"
    prefix:   /admin/badge

game_admin_quest:
    resource: "@GameBundle/Resources/config/routing/quest.yml"
    prefix:   /admin/quest

game_admin_claimed_quest:
    resource: "@GameBundle/Resources/config/routing/claimed-quest.yml"
    prefix:   /admin/claimed-quest

game_admin_claimed_badge:
    resource: "@GameBundle/Resources/config/routing/claimed-badge.yml"
    prefix:   /admin/claimed-badge

game_admin_unlocked_badge:
    resource: "@GameBundle/Resources/config/routing/unlocked-badge.yml"
    prefix:   /admin/unlocked-badge

game_admin_adventure:
    resource: "@GameBundle/Resources/config/routing/adventure.yml"
    prefix:   /admin/adventure

game_admin_claimed_adventure_step:
    resource: "@GameBundle/Resources/config/routing/claimed-adventure-step.yml"
    prefix:   /admin/claimed-adventure-step
