parameters:
    badger.game.saver.unlocked_badge.class: Badger\GameBundle\Doctrine\Saver\UnlockedBadgeSaver

services:
    badger.game.saver.badge:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\GameBundle\Entity\Badge'

    badger.game.saver.quest:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\GameBundle\Entity\Quest'

    badger.game.saver.unlocked_badge:
        class: '%badger.game.saver.unlocked_badge.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - 'Badger\GameBundle\Entity\UnlockedBadge'

    badger.game.saver.claimed_badge:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\GameBundle\Entity\ClaimedBadge'

    badger.game.saver.configuration:
        class: '%badger.storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\GameBundle\Entity\Configuration'

    badger.game.saver.badge_proposal:
        class: %badger.storage_utils.saver.base.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - 'Badger\GameBundle\Entity\BadgeProposal'
