parameters:
    badger.user_bundle.security.user_provider.class: Badger\UserBundle\Security\FOSUBUserProvider

services:
    badger.user_bundle.security.user_provider:
        class: "%badger.user_bundle.security.user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments:
            - '@fos_user.user_manager'
            - { github: github_id, google: google_id }
